# SPDX-License-Identifier: Apache-2.0
# Copyright (c) Arm Limited and Contributors
# Copyright (c) Intel Corporation
---
image:
  spdkcsi:
    repository: simplyblock/spdkcsi
    tag: latest
    pullPolicy: Always
  csiProvisioner:
    repository: registry.k8s.io/sig-storage/csi-provisioner
    tag: v3.5.0
    pullPolicy: Always
  csiAttacher:
    repository: gcr.io/k8s-staging-sig-storage/csi-attacher
    tag: v3.5.0
    pullPolicy: Always
  nodeDriverRegistrar:
    repository: registry.k8s.io/sig-storage/csi-node-driver-registrar
    tag: v2.8.0
    pullPolicy: Always
  csiSnapshotter:
    repository: registry.k8s.io/sig-storage/csi-snapshotter
    tag: v6.2.2
    pullPolicy: Always
  csiResizer:
    repository: gcr.io/k8s-staging-sig-storage/csi-resizer
    tag: v1.10.0
    pullPolicy: Always
  csiHealthMonitor:
    repository: gcr.io/k8s-staging-sig-storage/csi-external-health-monitor-controller
    tag: v0.10.0
    pullPolicy: Always
serviceAccount:
  # Specifies whether a serviceAccount should be created
  create: true

rbac:
  # Specifies whether RBAC resources should be created
  create: true

externallyManagedConfigmap:
  # Specifies whether a externallyManagedConfigmap should be created
  create: true

externallyManagedSecret:
  # Specifies whether a externallyManagedSecret should be created
  create: true

spdkdev:
  # Specifies whether a spdkdev should be created
  create: false

storageclass:
  create: true

controller:
  replicas: 1

# Configuration for the CSI to connect to the cluster
csiConfig:
  simplybk:
    uuid: 963c9d0a-4506-43c3-a722-0b7c8b157038
    ip: 13.58.2.30

# Configuration for the csiSecret
csiSecret:
  simplybk:
    secret: 2BAbQTPEDi4o73VHymg2

logicalVolume:
  pool_name: testing1
  qos_rw_iops: "0"
  qos_rw_mbytes: "0"
  qos_r_mbytes: "0"
  qos_w_mbytes: "0"
  compression: "False"
  encryption: "False"
  distr_ndcs: "1"
  distr_npcs: "1"

spdkdevCreateCommonds:
  /root/spdk/app/spdk_tgt/spdk_tgt > /tmp/spdk-tgt.log 2>&1 &
  echo wait 5s... && sleep 5s && cd /root/spdk/scripts &&
  ./rpc.py bdev_malloc_create -b Malloc0 1024 4096 &&
  ./rpc.py bdev_lvol_create_lvstore Malloc0 lvs0 &&
  ./rpc_http_proxy.py 127.0.0.1 9009 spdkcsiuser spdkcsipass

driverName: csi.spdk.io

benchmarks: 2
