{{- if .Values.cachingnode.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: caching-node-sa

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: caching-node-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "delete"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pods-list-cn
subjects:
- kind: ServiceAccount
  name: caching-node-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: caching-node-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: caching-node-ds
  annotations:
    helm.sh/hook: post-install
spec:
  selector:
    matchLabels:
      app: caching-node
  template:
    metadata:
      labels:
        app: caching-node
    spec:
      serviceAccountName: caching-node-sa
      nodeSelector:
        type: {{ .Values.cachingnode.nodeSelector }}
      volumes:
        - name: dev-vol
          hostPath:
            path: /dev
        - name: host-root
          hostPath:
            path: /

      hostNetwork: true
      {{- if .Values.cachingnode.tolerations.create }}
      tolerations:
      - operator: {{ .Values.cachingnode.tolerations.operator }}
        {{- if .Values.cachingnode.tolerations.effect }}
        effect: {{ .Values.cachingnode.tolerations.effect }}
        {{- end }}
        {{- if .Values.cachingnode.tolerations.key }}
        key: {{ .Values.cachingnode.tolerations.key }}
        {{- end }}
        {{- if .Values.cachingnode.tolerations.value }}
        value: {{ .Values.cachingnode.tolerations.value }}
        {{- end }}
      {{- end }}
      initContainers:
      - name: init-cnode
        image: "{{ .Values.image.simplyblock.repository }}:{{ .Values.image.simplyblock.tag }}"
        imagePullPolicy: "{{ .Values.image.simplyblock.pullPolicy }}"
        securityContext:
          privileged: true
        volumeMounts:
        - name: host-root
          mountPath: /host
        command:
        - "/bin/sh"
        - "-c"
        - |
          chroot /host /bin/sh -c '
          modprobe nbd
          sysctl -w vm.nr_hugepages={{ .Values.cachingnode.numhugepages }}
          systemctl restart kubelet
          yum install -y pciutils'
      containers:
      - name: c-node-api-container
        image: "{{ .Values.image.simplyblock.repository }}:{{ .Values.image.simplyblock.tag }}"
        imagePullPolicy: "{{ .Values.image.simplyblock.pullPolicy }}"
        command: ["python", "simplyblock_web/caching_node_app_k8s.py"]
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          privileged: true
        volumeMounts:
        - name: dev-vol
          mountPath: /dev

{{- end -}}
