{{- if or .Values.cachingnode.create .Values.storagenode.create -}}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: simplyblock-pod-listing-role-binding
subjects:
{{- if .Values.cachingnode.create }}
- kind: ServiceAccount
  name: caching-node-service-account
  namespace: {{ .Release.Namespace }}
{{- end }}
{{- if .Values.storagenode.create }}
- kind: ServiceAccount
  name: storage-node-service-account
  namespace: {{ .Release.Namespace }}
{{- end }}
roleRef:
  kind: ClusterRole
  name: simplyblock-pod-listing-role
  apiGroup: rbac.authorization.k8s.io

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: simplyblock-pod-listing-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]

{{- end -}}
