# SPDX-License-Identifier: Apache-2.0
# Copyright (c) Arm Limited and Contributors
# Copyright (c) Intel Corporation

{{- if .Values.externallyManagedSecret }}
---
apiVersion: v1
kind: Secret
metadata: 
  name: simplyblock-pvc-keys
  namespace: {{ .Release.Namespace }}
data:
  crypto_key1: {{ .Values.csiSecret.simplybkPvc.crypto_key1 }}
  crypto_key2: {{ .Values.csiSecret.simplybkPvc.crypto_key2 }}

---
apiVersion: v1
kind: Secret
metadata:
  name: simplyblock-csi-secret
stringData:
  secret.json: |-
{{ toJson .Values.csiSecret | indent 4 -}}
{{- end }}
