---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: storage-node-sa

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: storage-node-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "delete"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pods-list-sn
subjects:
- kind: ServiceAccount
  name: storage-node-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: storage-node-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: storage-node-ds
  annotations:
    helm.sh/hook: post-install
spec:
  selector:
    matchLabels:
      app: storage-node
  template:
    metadata:
      labels:
        app: storage-node
    spec:
      serviceAccountName: storage-node-sa
      nodeSelector:
        type: simplyblock-storage-plane
      volumes:
        - name: dev-vol
          hostPath:
            path: /dev
      hostNetwork: true
      {{- if .Values.storagenode.tolerations.create }}
      tolerations:
      - effect: {{ .Values.storagenode.tolerations.effect }}
        key: {{ .Values.storagenode.tolerations.key }}
        operator: {{ .Values.storagenode.tolerations.operator }}
        value: {{ .Values.storagenode.tolerations.value }}
      {{- end }}
      containers:
      - name: s-node-api-container
        image: "{{ .Values.image.simplyblock.repository }}:{{ .Values.image.simplyblock.tag }}"
        imagePullPolicy: "Always"
        command: ["python", "simplyblock_web/snode_app_k8s.py"]
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          privileged: true
        volumeMounts:
        - name: dev-vol
          mountPath: /dev

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: storage-node-ds-reserve
  annotations:
    helm.sh/hook: post-install
spec:
  selector:
    matchLabels:
      app: storage-node-reserve
  template:
    metadata:
      labels:
        app: storage-node-reserve
    spec:
      serviceAccountName: storage-node-sa
      nodeSelector:
        type: simplyblock-storage-plane
      volumes:
        - name: dev-vol
          hostPath:
            path: /dev
      hostNetwork: true
      {{- if .Values.storagenode.tolerations.create }}
      tolerations:
      - effect: {{ .Values.storagenode.tolerations.effect }}
        key: {{ .Values.storagenode.tolerations.key }}
        operator: {{ .Values.storagenode.tolerations.operator }}
        value: {{ .Values.storagenode.tolerations.value }}
      {{- end }}
      containers:
      - name: s-node-api-container
        image: "{{ .Values.image.simplyblock.repository }}:{{ .Values.image.simplyblock.tag }}"
        imagePullPolicy: "Always"
        command: ["python", "simplyblock_web/snode_app_k8s.py"]
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          privileged: true
        volumeMounts:
        - name: dev-vol
          mountPath: /dev
