apiVersion: v1
entries:
  sb-controller:
  spdk-csi:
  - apiVersion: v1
    appVersion: latest
    created: "2025-04-29T12:14:28.668182956Z"
    description: Simplyblock CSI Driver for Kubernetes
    digest: 2f14b7dcbc2c1b9d340b952846182e6eb505223069997b0db42b139d2b1db388
    home: https://github.com/simplyblock-io/spdk-csi
    keywords:
    - spdk
    - csi
    - spdk-csi
    name: spdk-csi
    sources:
    - https://github.com/simplyblock-io/spdk-csi/tree/master/charts/spdk-csi
    urls:
    - https://github.com/simplyblock-io/spdk-csi/raw/master/charts/spdk-csi/v0.3.16/spdk-csi-v0.3.16.tgz
    version: v0.3.16
  - apiVersion: v1
    appVersion: latest
    created: "2025-04-29T12:14:28.667217546Z"
    description: Simplyblock CSI Driver for Kubernetes
    digest: 825c29d045abb878ac14d551d579abe034220d18ead8f074cd42c35851d8e9ad
    home: https://github.com/simplyblock-io/spdk-csi
    keywords:
    - spdk
    - csi
    - spdk-csi
    name: spdk-csi
    sources:
    - https://github.com/simplyblock-io/spdk-csi/tree/master/charts/spdk-csi
    urls:
    - https://github.com/simplyblock-io/spdk-csi/raw/master/charts/spdk-csi/v0.3.15/spdk-csi-v0.3.15.tgz
    version: v0.3.15
  - apiVersion: v1
    appVersion: latest
    created: "2025-04-29T12:14:28.666227861Z"
    description: Simplyblock CSI Driver for Kubernetes
    digest: 33ef4568e8fc1c17c5eb946bde0ce55003f0fa1ab511854efd2e402ff478ab66
    home: https://github.com/simplyblock-io/spdk-csi
    keywords:
    - spdk
    - csi
    - spdk-csi
    name: spdk-csi
    sources:
    - https://github.com/simplyblock-io/spdk-csi/tree/master/charts/spdk-csi
    urls:
    - https://github.com/simplyblock-io/spdk-csi/raw/master/charts/spdk-csi/v0.3.14/spdk-csi-v0.3.14.tgz
    version: v0.3.14
  - apiVersion: v1
    appVersion: latest
    created: "2025-04-29T12:14:28.665238888Z"
    description: Simplyblock CSI Driver for Kubernetes
    digest: 4118557051bc3617840c7cded6599cb7701541a2060b76a8445589f59aa1f0b6
    home: https://github.com/simplyblock-io/spdk-csi
    keywords:
    - spdk
    - csi
    - spdk-csi
    name: spdk-csi
    sources:
    - https://github.com/simplyblock-io/spdk-csi/tree/master/charts/spdk-csi
    urls:
    - https://github.com/simplyblock-io/spdk-csi/raw/master/charts/spdk-csi/v0.3.13/spdk-csi-v0.3.13.tgz
    version: v0.3.13
  - apiVersion: v1
    appVersion: latest
    created: "2025-04-29T12:14:28.663503983Z"
    description: Simplyblock CSI Driver for Kubernetes
    digest: f24ec5f2d3a786966e26604fc1cd6b0b55947acfe54ca7c7654bf2556f73e4e6
    home: https://github.com/simplyblock-io/spdk-csi
    keywords:
    - spdk
    - csi
    - spdk-csi
    name: spdk-csi
    sources:
    - https://github.com/simplyblock-io/spdk-csi/tree/master/charts/spdk-csi
    urls:
    - https://github.com/simplyblock-io/spdk-csi/raw/master/charts/spdk-csi/v0.3.12/spdk-csi-v0.3.12.tgz
    version: v0.3.12
  - apiVersion: v1
    appVersion: latest
    created: "2025-04-29T12:14:28.662532733Z"
    description: Simplyblock CSI Driver for Kubernetes
    digest: 861fd5c8aee948979ac240909ff542ee26174eb9f2cce9ca4c60338a39c7202c
    home: https://github.com/simplyblock-io/spdk-csi
    keywords:
    - spdk
    - csi
    - spdk-csi
    name: spdk-csi
    sources:
    - https://github.com/simplyblock-io/spdk-csi/tree/master/charts/spdk-csi
    urls:
    - https://github.com/simplyblock-io/spdk-csi/raw/master/charts/spdk-csi/v0.3.11/spdk-csi-v0.3.11.tgz
    version: v0.3.11
  - apiVersion: v1
    appVersion: latest
    created: "2025-04-29T12:14:28.660945614Z"
    description: Simplyblock CSI Driver for Kubernetes
    digest: 673e77eebef77f869d92199a841eb1a50669e122fbbaacde9ba6709d098f77e1
    home: https://github.com/simplyblock-io/spdk-csi
    keywords:
    - spdk
    - csi
    - spdk-csi
    name: spdk-csi
    sources:
    - https://github.com/simplyblock-io/spdk-csi/tree/master/charts/spdk-csi
    urls:
    - https://github.com/simplyblock-io/spdk-csi/raw/master/charts/spdk-csi/v0.3.10/spdk-csi-v0.3.10.tgz
    version: v0.3.10
  - apiVersion: v1
    appVersion: latest
    created: "2025-04-29T12:14:28.676296533Z"
    description: Simplyblock CSI Driver for Kubernetes
    digest: 43d9bedad3a6bfa69968423075d67ebc273680446bb6683d4204ef62e1e36c80
    home: https://github.com/simplyblock-io/spdk-csi
    keywords:
    - spdk
    - csi
    - spdk-csi
    name: spdk-csi
    sources:
    - https://github.com/simplyblock-io/spdk-csi/tree/master/charts/spdk-csi
    urls:
    - https://github.com/simplyblock-io/spdk-csi/raw/master/charts/spdk-csi/v0.3.9/spdk-csi-v0.3.9.tgz
    version: v0.3.9
  - apiVersion: v1
    appVersion: latest
    created: "2025-04-29T12:14:28.675395814Z"
    description: Simplyblock CSI Driver for Kubernetes
    digest: 6bce73c847870fe9bd6556d0efef733617a579172f0f6ca48090230b50a04143
    home: https://github.com/simplyblock-io/spdk-csi
    keywords:
    - spdk
    - csi
    - spdk-csi
    name: spdk-csi
    sources:
    - https://github.com/simplyblock-io/spdk-csi/tree/master/charts/spdk-csi
    urls:
    - https://github.com/simplyblock-io/spdk-csi/raw/master/charts/spdk-csi/v0.3.8/spdk-csi-v0.3.8.tgz
    version: v0.3.8
  - apiVersion: v1
    appVersion: latest
    created: "2025-04-29T12:14:28.674509692Z"
    description: Simplyblock CSI Driver for Kubernetes
    digest: e67a2810c0c0825b31ee775ff6b9dabd25ed528ad7758a05fb80d65498f90878
    home: https://github.com/simplyblock-io/spdk-csi
    keywords:
    - spdk
    - csi
    - spdk-csi
    name: spdk-csi
    sources:
    - https://github.com/simplyblock-io/spdk-csi/tree/master/charts/spdk-csi
    urls:
    - https://github.com/simplyblock-io/spdk-csi/raw/master/charts/spdk-csi/v0.3.7/spdk-csi-v0.3.7.tgz
    version: v0.3.7
  - apiVersion: v1
    appVersion: latest
    created: "2025-04-29T12:14:28.6736073Z"
    description: Simplyblock CSI Driver for Kubernetes
    digest: 46ddc4f5f6a982eb470bfaec3c664752a13a5d5d84dc61327aaa1922783404cf
    home: https://github.com/simplyblock-io/spdk-csi
    keywords:
    - spdk
    - csi
    - spdk-csi
    name: spdk-csi
    sources:
    - https://github.com/simplyblock-io/spdk-csi/tree/master/charts/spdk-csi
    urls:
    - https://github.com/simplyblock-io/spdk-csi/raw/master/charts/spdk-csi/v0.3.6/spdk-csi-v0.3.6.tgz
    version: v0.3.6
  - apiVersion: v1
    appVersion: latest
    created: "2025-04-29T12:14:28.67267415Z"
    description: Simplyblock CSI Driver for Kubernetes
    digest: 63091b6ff510f80e554df911b1aaac5847a1346a575a1390b71410490a0f763b
    home: https://github.com/simplyblock-io/spdk-csi
    keywords:
    - spdk
    - csi
    - spdk-csi
    name: spdk-csi
    sources:
    - https://github.com/simplyblock-io/spdk-csi/tree/master/charts/spdk-csi
    urls:
    - https://github.com/simplyblock-io/spdk-csi/raw/master/charts/spdk-csi/v0.3.5/spdk-csi-v0.3.5.tgz
    version: v0.3.5
  - apiVersion: v1
    appVersion: latest
    created: "2025-04-29T12:14:28.670740203Z"
    description: Simplyblock CSI Driver for Kubernetes
    digest: 3a66e531d2879771daeb1498441ac1310fbfb4c8d31ec9c351e9849d004f3aac
    home: https://github.com/simplyblock-io/spdk-csi
    keywords:
    - spdk
    - csi
    - spdk-csi
    name: spdk-csi
    sources:
    - https://github.com/simplyblock-io/spdk-csi/tree/master/charts/spdk-csi
    urls:
    - https://github.com/simplyblock-io/spdk-csi/raw/master/charts/spdk-csi/v0.3.4/spdk-csi-v0.3.4.tgz
    version: v0.3.4
  - apiVersion: v1
    appVersion: latest
    created: "2025-04-29T12:14:28.669889708Z"
    description: Simplyblock CSI Driver for Kubernetes
    digest: b83a89ac558b464eaef296e6317473b7f26514d5a8a7f79aa2acd61da069f3d0
    home: https://github.com/simplyblock-io/spdk-csi
    keywords:
    - spdk
    - csi
    - spdk-csi
    name: spdk-csi
    sources:
    - https://github.com/simplyblock-io/spdk-csi/tree/master/charts/spdk-csi
    urls:
    - https://github.com/simplyblock-io/spdk-csi/raw/master/charts/spdk-csi/v0.3.3/spdk-csi-v0.3.3.tgz
    version: v0.3.3
  - apiVersion: v1
    appVersion: latest
    created: "2025-04-29T12:14:28.669036087Z"
    description: Simplyblock CSI Driver for Kubernetes
    digest: 86b5d9c79c06e8184775c7c41c6dfe175c6f4fa5d0e92910f71e2bf1874858b6
    home: https://github.com/simplyblock-io/spdk-csi
    keywords:
    - spdk
    - csi
    - spdk-csi
    name: spdk-csi
    sources:
    - https://github.com/simplyblock-io/spdk-csi/tree/master/charts/spdk-csi
    urls:
    - https://github.com/simplyblock-io/spdk-csi/raw/master/charts/spdk-csi/v0.3.2/spdk-csi-v0.3.2.tgz
    version: v0.3.2
  - apiVersion: v1
    appVersion: latest
    created: "2025-04-29T12:14:28.660008978Z"
    description: Simplyblock CSI Driver for Kubernetes
    digest: c362b8f3ba046743c11099443b1091b64cb6c27c42aef6b71a483934664a7fde
    home: https://github.com/simplyblock-io/spdk-csi
    keywords:
    - spdk
    - csi
    - spdk-csi
    name: spdk-csi
    sources:
    - https://github.com/simplyblock-io/spdk-csi/tree/master/charts/spdk-csi
    urls:
    - https://github.com/simplyblock-io/spdk-csi/raw/master/charts/spdk-csi/v0.3.1/spdk-csi-v0.3.1.tgz
    version: v0.3.1
  - apiVersion: v1
    appVersion: latest
    created: "2025-04-29T12:14:28.659502654Z"
    description: Simplyblock CSI Driver for Kubernetes
    digest: c7999217b515f9ba4f2a8f5a2a025a3d40d42f21f75af1621043b5a356ab1ac9
    home: https://github.com/simplyblock-io/spdk-csi
    keywords:
    - spdk
    - csi
    - spdk-csi
    name: spdk-csi
    sources:
    - https://github.com/simplyblock-io/spdk-csi/tree/master/charts/spdk-csi
    urls:
    - https://github.com/simplyblock-io/spdk-csi/raw/master/charts/spdk-csi/v0.3.0/spdk-csi-v0.3.0.tgz
    version: v0.3.0
  - apiVersion: v1
    appVersion: latest
    created: "2025-04-29T12:14:28.657930563Z"
    description: SimplyBlock CSI Driver for Kubernetes
    digest: 72152d66d4368a94e55a3fbd675aac95aa6aeb916b4d3c40c205106cfefe3cd8
    home: https://github.com/simplyblock-io/spdk-csi
    keywords:
    - spdk
    - csi
    - spdk-csi
    name: spdk-csi
    sources:
    - https://github.com/simplyblock-io/spdk-csi/tree/master/charts/spdk-csi
    urls:
    - https://github.com/simplyblock-io/spdk-csi/raw/master/charts/spdk-csi/v0.1.0/spdk-csi-v0.1.0.tgz
    version: "0.2"
  - apiVersion: v1
    appVersion: latest
    created: "2025-04-29T12:14:28.658976734Z"
    description: Simplyblock CSI Driver for Kubernetes
    digest: 61e39d280742808fef5f13841be0ea4f6c0a1ae5de61668b690f4879afe4ce55
    home: https://github.com/simplyblock-io/spdk-csi
    keywords:
    - spdk
    - csi
    - spdk-csi
    name: spdk-csi
    sources:
    - https://github.com/simplyblock-io/spdk-csi/tree/master/charts/spdk-csi
    urls:
    - https://github.com/simplyblock-io/spdk-csi/raw/master/charts/spdk-csi/v0.2.0/spdk-csi-v0.2.0.tgz
    version: v0.2.0
  - apiVersion: v1
    appVersion: latest
    created: "2025-04-29T12:14:28.658467484Z"
    description: SimplyBlock CSI Driver for Kubernetes
    digest: 8b9cbf2435eb706000edd6a08f3916093a9eb724ad6a5e215019c4b8412d05e5
    home: https://github.com/simplyblock-io/spdk-csi
    keywords:
    - spdk
    - csi
    - spdk-csi
    name: spdk-csi
    sources:
    - https://github.com/simplyblock-io/spdk-csi/tree/master/charts/spdk-csi
    urls:
    - https://github.com/simplyblock-io/spdk-csi/raw/master/charts/spdk-csi/v0.1.1/spdk-csi-v0.1.1.tgz
    version: v0.1.1
generated: "2025-04-29T12:14:28.657243863Z"
