{{- if .Values.cachingnode.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: simplyblock-caching-node-sa

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: simplyblock-caching-node-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "delete"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pods-list-cn
subjects:
- kind: ServiceAccount
  name: simplyblock-caching-node-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: simplyblock-caching-node-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: simplyblock-caching-node-ds
  annotations:
    {{- with .Values.simplyBlockAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app: caching-node
  template:
    metadata:
      labels:
        app: caching-node
      annotations:
        {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
    spec:
      serviceAccountName: simplyblock-caching-node-sa
      nodeSelector:
        {{ .Values.cachingnode.nodeSelector.key }}: {{ .Values.cachingnode.nodeSelector.value }}
      volumes:
        - name: dev-vol
          hostPath:
            path: /dev

      hostNetwork: true
      {{- if .Values.cachingnode.tolerations.create }}
      tolerations:
      - operator: {{ .Values.cachingnode.tolerations.operator }}
        {{- if .Values.cachingnode.tolerations.effect }}
        effect: {{ .Values.cachingnode.tolerations.effect }}
        {{- end }}
        {{- if .Values.cachingnode.tolerations.key }}
        key: {{ .Values.cachingnode.tolerations.key }}
        {{- end }}
        {{- if .Values.cachingnode.tolerations.value }}
        value: {{ .Values.cachingnode.tolerations.value }}
        {{- end }}
      {{- end }}
      containers:
      - name: c-node-api-container
        image: "{{ .Values.image.simplyblock.repository }}:{{ .Values.image.simplyblock.tag }}"
        imagePullPolicy: "{{ .Values.image.simplyblock.pullPolicy }}"
        command: ["python", "simplyblock_web/node_webapp.py", "caching_kubernetes_node"]
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          privileged: true
        volumeMounts:
        - name: dev-vol
          mountPath: /dev

{{- end -}}
