{{- if .Values.storagenode.create -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: simplyblock-storage-pdb
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      app: storage-node
      role: simplyblock-storage-node
{{- end -}}
