{{- if .Values.storagenode.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: simplyblock-storage-node-sa

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: simplyblock-storage-node-role
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces", "pods/exec"]
  verbs: ["list", "get", "create", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "delete"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: simplyblock-pods-list-sn
subjects:
- kind: ServiceAccount
  name: simplyblock-storage-node-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: simplyblock-storage-node-role
  apiGroup: rbac.authorization.k8s.io

{{- range .Values.storagenode.daemonsets }}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .name }}
spec:
  selector:
    matchLabels:
      app: {{ .appLabel }}
  template:
    metadata:
      labels:
        app: {{ .appLabel }}
    spec:
      serviceAccountName: simplyblock-storage-node-sa
      nodeSelector:
        {{ .nodeSelector.key }}: {{ .nodeSelector.value }}
      volumes:
        - name: dev-vol
          hostPath:
            path: /dev
        - name: etc-simplyblock
          hostPath:
            path: /var/simplyblock
      hostNetwork: true
      {{- if .tolerations.create }}
      tolerations:
      - operator: {{ .tolerations.operator }}
        {{- if .tolerations.effect }}
        effect: {{ .tolerations.effect }}
        {{- end }}
        {{- if .tolerations.key }}
        key: {{ .tolerations.key }}
        {{- end }}
        {{- if .tolerations.value }}
        value: {{ .tolerations.value }}
        {{- end }}
      {{- end }}
      initContainers:
      - name: s-node-api-config-generator
        image: "{{ $.Values.image.simplyblock.repository }}:{{ $.Values.image.simplyblock.tag }}"
        imagePullPolicy: "{{ $.Values.image.simplyblock.pullPolicy }}"
        command:
          - "python"
          - "simplyblock_web/node_configure.py"
          - "--max-lvol={{ $.Values.storagenode.maxLvol }}"
          - "--max-size={{ $.Values.storagenode.maxProv }}"
          {{- if $.Values.storagenode.pciAllowed }}
          - "--pci-allowed={{ $.Values.storagenode.pciAllowed }}"
          {{- end }}
          {{- if $.Values.storagenode.pciBlocked }}
          - "--pci-blocked={{ $.Values.storagenode.pciBlocked }}"
          {{- end }}
          {{- if $.Values.storagenode.socketsToUse }}
          - "--sockets-to-use={{ $.Values.storagenode.socketsToUse }}"
          {{- end }}
          {{- if $.Values.storagenode.nodesPerSocket }}
          - "--nodes-per-socket={{ $.Values.storagenode.nodesPerSocket }}"
          {{- end }}
        volumeMounts:
          - name: etc-simplyblock
            mountPath: /etc/simplyblock
        securityContext:
          privileged: true
      containers:
      - name: s-node-api-container
        image: "{{ $.Values.image.simplyblock.repository }}:{{ $.Values.image.simplyblock.tag }}"
        imagePullPolicy: "{{ $.Values.image.simplyblock.pullPolicy }}"
        command: ["python", "simplyblock_web/node_webapp.py", "storage_node_k8s"]
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: CPUMASK
          value: "{{ $.Values.storagenode.cpuMask }}"
        securityContext:
          privileged: true
        volumeMounts:
        - name: dev-vol
          mountPath: /dev
        - name: etc-simplyblock
          mountPath: /etc/simplyblock
        livenessProbe:
          httpGet:
            path: /snode/get_firewall
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /snode/get_firewall
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 5
          failureThreshold: 3

{{- end }}

{{- end -}}
