kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: spdkcsi-cache-pvc3
  annotations:
    simplybk/secret-name: simplyblock-pvc-keys
    simplybk/secret-namespace: default
    #simplybk/host-id: 1678ca3e-f02a-4855-ac8f-95e3bd8e2362
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
  storageClassName: spdkcsi-sc-cache
