kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: spdkcsi-cache-pvc
  annotations:
    simplybk/secret-name: simplyblock-pvc-keys
    simplybk/secret-namespace: default
    
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
  storageClassName: spdkcsi-sc-cache
