apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    annotations:
        simplybk/secret-name: simplyblock-pvc-keys
        simplybk/secret-namespace: default
    name: spdkcsi-pvc
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 256Mi
    storageClassName: spdkcsi-sc
