# SPDX-License-Identifier: Apache-2.0
# Copyright (c) Arm Limited and Contributors
# Copyright (c) Intel Corporation
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spdkcsi-pvc
  annotations:
    simplybk/secret-name: simplyblock-pvc-keys
    simplybk/secret-namespace: default
    #simplybk/host-id: 4942145f-68e7-4b11-ab1c-11dae7b867ed
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
  storageClassName: spdkcsi-sc
