# SPDX-License-Identifier: Apache-2.0
# Copyright (c) Arm Limited and Contributors
# Copyright (c) Intel Corporation

{{- if .Values.externallyManagedConfigmap }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spdkcsi-cm
data:
  # uuid: the simplyblock cluster UUID
  # ip: the management IP of the simplyblock cluster
  # targetAddr: target service IP
  config.json: |-
{{ toJson .Values.csiConfig | indent 4 -}}
{{- end }}
