kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-listing-role-binding
subjects:
- kind: ServiceAccount
  name: caching-node-service-account
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: pod-listing-role
  apiGroup: rbac.authorization.k8s.io

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-listing-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: caching-node-service-account
---
apiVersion: batch/v1
kind: Job
metadata:
  name: add-caching-node-job
spec:
  template:
    spec:
      serviceAccountName: caching-node-service-account
      volumes:
        - name: script-config
          configMap:
            name: add-caching-node-script-cm
      containers:
      - name: add-caching-node
        image: python:3.10
        command: ["python3", "/config/add_cn_script.py"]
        env:
        - name: SPDKCSI_SECRET
          valueFrom:
            secretKeyRef:
              name: spdkcsi-secret
              key: secret.json
        - name: CLUSTER_CONFIG
          valueFrom:
            configMapKeyRef:
              name: spdkcsi-cm
              key: config.json
        volumeMounts:
            - name: script-config
              mountPath: /config
      restartPolicy: Never
  backoffLimit: 4
