---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: full-access
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["*"]
  verbs: ["*"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pods-list
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: ClusterRole
  name: full-access
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: caching-node-deployment
spec:
  selector:
    matchLabels:
      app: caching-node
  template:
    metadata:
      labels:
        app: caching-node
    spec:
      volumes:
        - name: dev-vol
          hostPath:
            path: /dev
      hostNetwork: true
      containers:
      - name: c-node-api-container
        image: hamdykhader/simplyblock:latest
        imagePullPolicy: "Always"
        command: ["python", "WebApp/caching_node_app_k8s.py"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: dev-vol
          mountPath: /dev
