# SPDX-License-Identifier: Apache-2.0
# Copyright (c) Arm Limited and Contributors
# Copyright (c) Intel Corporation
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spdkcsi-cm
data:
  config.json: |-
    {
      "simplybk": {
        "uuid": "1a215589-e08f-47aa-bafb-3ee68d719e35",
        "ip": "3.140.238.66"
      }
    }
