# SPDX-License-Identifier: Apache-2.0
# Copyright (c) Arm Limited and Contributors
# Copyright (c) Intel Corporation
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spdkcsi-cm
data:
  config.json: |-
    {
      "simplybk": {
        "uuid": "624455a7-ff5a-4fb1-b604-738675a6c9d8",
        "ip": "3.222.192.14"
      }
    }
