# SPDX-License-Identifier: Apache-2.0
# Copyright (c) Arm Limited and Contributors
# Copyright (c) Intel Corporation
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spdkcsi-cm
data:
  config.json: |-
    {
      "simplybk": {
        "uuid": "79276661-5f8a-405d-ab6d-651b88326206",
        "ip": "18.218.243.112"
      }
    }
