# SPDX-License-Identifier: Apache-2.0
# Copyright (c) Arm Limited and Contributors
# Copyright (c) Intel Corporation
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spdkcsi-cm
data:
  # rpcURL: spdk json rpc target
  # targetType: nvme-rdma, nvme-tcp, iscsi
  # targetAddr: target service IP
  config.json: |-
    {
      "nodes": [
        {
          "name": "pool1",
          "rpcURL": "http://34.244.195.34",
          "targetType": "nvme-tcp",
          "targetAddr": "127.0.0.1"
        }
      ]
    }
