# SPDX-License-Identifier: Apache-2.0
# Copyright (c) Arm Limited and Contributors
# Copyright (c) Intel Corporation
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spdkcsi-cm
data:
  # rpcURL: spdk json rpc target
  # targetType: nvme-rdma, nvme-tcp, iscsi
  # targetAddr: target service IP
  config.json: |-
    {
      "simplybk": {
        "uuid": "19177288-d3c2-46da-addb-87bab9948193",
        "ip": "176.34.160.206"
      }
    }
