# SPDX-License-Identifier: Apache-2.0
# Copyright (c) Arm Limited and Contributors
# Copyright (c) Intel Corporation
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spdkcsi-cm
data:
  config.json: |-
    {
      "simplybk": {
        "uuid": "b2220b8a-dd09-4c2e-8163-3f85d7c12736",
        "ip": "10.0.1.207"
      }
    }
