# SPDX-License-Identifier: Apache-2.0
# Copyright (c) Arm Limited and Contributors
# Copyright (c) Intel Corporation
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: spdkcsi-controller
spec:
  serviceName: spdkcsi-controller
  replicas: 1
  selector:
    matchLabels:
      app: spdkcsi-controller
  template:
    metadata:
      labels:
        app: spdkcsi-controller
    spec:
      serviceAccountName: spdkcsi-controller-sa
      hostNetwork: true
      containers:
      - name: spdkcsi-provisioner
        image: registry.k8s.io/sig-storage/csi-provisioner:v3.5.0
        imagePullPolicy: "IfNotPresent"
        args:
        - "--v=5"
        - "--csi-address=unix:///csi/csi-provisioner.sock"
        - "--timeout=30s"
        - "--retry-interval-start=500ms"
        - "--leader-election=false"
        - "--feature-gates=Topology=true"
        volumeMounts:
        - name: socket-dir
          mountPath: /csi
      - name: spdkcsi-snapshotter
        image: registry.k8s.io/sig-storage/csi-snapshotter:v6.2.2
        args:
        - "--csi-address=unix:///csi/csi-provisioner.sock"
        - "--v=5"
        - "--timeout=150s"
        - "--leader-election=false"
        imagePullPolicy: "IfNotPresent"
        securityContext:
          privileged: true
        volumeMounts:
        - name: socket-dir
          mountPath: /csi
      - name: spdkcsi-attacher
        image: gcr.io/k8s-staging-sig-storage/csi-attacher:v3.5.0
        imagePullPolicy: "IfNotPresent"
        args:
        - "--v=5"
        - "--csi-address=unix:///csi/csi-provisioner.sock"
        - "--leader-election=false"
        volumeMounts:
        - name: socket-dir
          mountPath: /csi
      - name: spdkcsi-resizer
        image: gcr.io/k8s-staging-sig-storage/csi-resizer:v1.10.0
        imagePullPolicy: "IfNotPresent"
        args:
          - "--v=5"
          - "--csi-address=unix:///csi/csi-provisioner.sock"
          - "--leader-election=false"
        volumeMounts:
          - name: socket-dir
            mountPath: /csi

      - name: spdkcsi-controller
        image: manoharbrm/spdkcsi:latest
        imagePullPolicy: "Always"
        args:
        - "--v=5"
        - "--endpoint=unix:///csi/csi-provisioner.sock"
        - "--nodeid=$(NODE_ID)"
        - "--controller"
        env:
        - name: NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: socket-dir
          mountPath: /csi
        - name: spdkcsi-config
          mountPath: /etc/spdkcsi-config/
          readOnly: true
        - name: spdkcsi-secret
          mountPath: /etc/spdkcsi-secret/
          readOnly: true
      volumes:
      - name: socket-dir
        emptyDir:
          medium: "Memory"
      - name: spdkcsi-config
        configMap:
          name: spdkcsi-cm
      - name: spdkcsi-secret
        secret:
          secretName: spdkcsi-secret
