# SPDX-License-Identifier: Apache-2.0
# Copyright (c) Arm Limited and Contributors
# Copyright (c) Intel Corporation
---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: csi.spdk.io
spec:
  attachRequired: true
  volumeLifecycleModes:
  - Persistent
