# SPDX-License-Identifier: Apache-2.0
# Copyright (c) Arm Limited and Contributors
# Copyright (c) Intel Corporation
---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: spdkcsi-node
spec:
  selector:
    matchLabels:
      app: spdkcsi-node
  template:
    metadata:
      labels:
        app: spdkcsi-node
    spec:
      serviceAccountName: spdkcsi-node-sa
      hostNetwork: true
      containers:
      - name: spdkcsi-registrar
        securityContext:
          privileged: true
        image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.8.0
        imagePullPolicy: "IfNotPresent"
        args:
        - "--v=5"
        - "--csi-address=unix:///csi/csi.sock"
        - "--kubelet-registration-path=/var/lib/kubelet/plugins/csi.spdk.io/csi.sock"
        volumeMounts:
        - name: socket-dir
          mountPath: /csi
        - name: registration-dir
          mountPath: /registration
      - name: spdkcsi-node
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN", "SYS_MODULE"]
          allowPrivilegeEscalation: true
        image: simplyblock/spdkcsi:pr-14-7170fc88
        imagePullPolicy: "Always"
        args:
        - "--v=5"
        - "--endpoint=unix:///csi/csi.sock"
        - "--nodeid=$(NODE_ID)"
        - "--node"
        env:
        - name: NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "sudo modprobe nvme-tcp || echo failed to modprobe nvme-tcp"]
        volumeMounts:
        - name: socket-dir
          mountPath: /csi
        - name: plugin-dir
          mountPath: /var/lib/kubelet/plugins
          mountPropagation: "Bidirectional"
        - name: pod-dir
          mountPath: /var/lib/kubelet/pods
          mountPropagation: "Bidirectional"
        - name: host-dev
          mountPath: /dev
        - name: host-sys
          mountPath: /sys
        - name: spdkcsi-nodeserver-config
          mountPath: /etc/spdkcsi-nodeserver-config/
          readOnly: true
        - name: spdkcsi-config
          mountPath: /etc/spdkcsi-config/
          readOnly: true
        - name: spdkcsi-secret
          mountPath: /etc/spdkcsi-secret/
          readOnly: true
      volumes:
      - name: socket-dir
        hostPath:
          path: /var/lib/kubelet/plugins/csi.spdk.io
          type: DirectoryOrCreate
      - name: registration-dir
        hostPath:
          path: /var/lib/kubelet/plugins_registry/
          type: Directory
      - name: plugin-dir
        hostPath:
          path: /var/lib/kubelet/plugins
          type: Directory
      - name: pod-dir
        hostPath:
          path: /var/lib/kubelet/pods
          type: Directory
      - name: host-dev
        hostPath:
          path: /dev
      - name: host-sys
        hostPath:
          path: /sys
      - name: spdkcsi-nodeserver-config
        configMap:
          name: spdkcsi-nodeservercm
          optional: true
      - name: spdkcsi-config
        configMap:
          name: spdkcsi-cm
      - name: spdkcsi-secret
        secret:
          secretName: spdkcsi-secret

