# SPDX-License-Identifier: Apache-2.0
# Copyright (c) Arm Limited and Contributors
# Copyright (c) Intel Corporation
---
apiVersion: v1
kind: Secret
metadata:
  name: spdkcsi-secret
stringData:
  # Specify node specific token with item "name" matches ConfigMap.
  # {
  #   "name": "spdk-testnode",
  #   "username": "myuser",
  #   "password": "mypass"
  # }
  secret.json: |-
    {
      "simplybk": {
        "secret": "RhOaHtnL7cr0kPXk7WD7"
      }
    }
---
apiVersion: v1
Kind: Secret
metadata: 
  name: simplyblock-pvc-keys
  namespace: simplyblock
data:
  crypto_key1: 7b3695268e2a6611a25ac4b1ee15f27f9bf6ea9783dada66a4a730ebf0492bfd
  crypto_key2: 78505636c8133d9be42e347f82785b81a879cd8133046f8fc0b36f17b078ad0c