# SPDX-License-Identifier: Apache-2.0
# Copyright (c) Arm Limited and Contributors
# Copyright (c) Intel Corporation
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: spdkcsi-sc
provisioner: csi.spdk.io
parameters:
  fsType: ext4
  pool_name: pool1
  qos_rw_iops: "0"
  qos_rw_mbytes: "0"
  qos_r_mbytes: "0"
  qos_w_mbytes: "0"
  compression: "False"
  encryption: "False"
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
