# SPDX-License-Identifier: Apache-2.0
# Copyright (c) Arm Limited and Contributors
# Copyright (c) Intel Corporation
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: spdkcsi-sc
provisioner: csi.spdk.io
parameters:
  csi.storage.k8s.io/fstype: ext4
  pool_name: testing0
  qos_rw_iops: "0"
  qos_rw_mbytes: "0"
  qos_r_mbytes: "0"
  qos_w_mbytes: "0"
  compression: "False"
  encryption: "False"
  distr-ndcs: "1"
  distr-npcs: "1"
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
