---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spdkcsi-pvc-restore
spec:
  storageClassName: spdkcsi-sc
  dataSource:
    name: spdk-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
