---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spdkcsi-pvc-restore
spec:
  storageClassName: spdkcsi-sc
  dataSource:
    name: spdk-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
kind: Pod
apiVersion: v1
metadata:
  name: spdkcsi-test
spec:
  containers:
  - name: alpine
    image: alpine:3
    imagePullPolicy: "IfNotPresent"
    command: ["sleep", "365d"]
    volumeMounts:
    - mountPath: "/spdkvol"
      name: spdk-volume
  volumes:
  - name: spdk-volume
    persistentVolumeClaim:
      claimName: spdkcsi-pvc-restore