name: Release Charts

on:
  push:
    branches:
      - master
    paths:
      - 'charts/latest/spdk-csi/Chart.yaml'
  
jobs:
  package-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.0

      - name: Extract version and package chart
        run: |
          cd charts/latest/
          VERSION="$(grep '^version:' spdk-csi/Chart.yaml | awk '{print $2}' | tr -d '"')"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

          helm package spdk-csi
          mkdir -p "../$VERSION"

          mv "spdk-csi-$VERSION.tgz" "../$VERSION/"

      - name: Update index.yaml
        run: |
          cd charts/
          helm repo index . --url https://github.com/simplyblock-io/spdk-csi/raw/master/charts

      - name: Commit and create PR
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          BRANCH="release-${{ env.VERSION }}"
          git checkout -b "$BRANCH"

          git add charts/index.yaml charts/${{ env.VERSION }}/
          git commit -m "helm release for simplyblock csi ${{ env.VERSION }}" || echo "No changes to commit"
          git push origin "$BRANCH"

          gh pr create \
            --title "Helm release: ${{ env.VERSION }}" \
            --body "Automated Helm release for simplyblock-csi ${{ env.VERSION}}" \
            --head "$BRANCH" \
            --base master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
