name: SPDK E2E TEST

on:
  workflow_dispatch:
    inputs:
      uuid:
        description: ''
        required: true
        default: '79276661-5f8a-405d-ab6d-651b88326206'
      ip:
        description: ''
        required: true
        default: '18.218.243.112'
      secret:
        description: ''
        required: true
        default: '8K9BVlNfYo6aiLamu1c2'
jobs:
  build:
    name: Build
    runs-on:  ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version: ^1.21
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
      
    - name: Install kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

    - name: Install Helm
      run: |
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh

    - name: Authenticate with Kubernetes cluster
      run: |
        mkdir -p "${HOME}/.kube"
        echo ${{ secrets.KUBE_CONFIG_DATA }} | base64 --decode >  ${HOME}/.kube/config

    # - name: Update ConfigMap
    #   run: |
    #     sed -i "s/\"uuid\": \".*\"/\"uuid\": \"${{ github.event.inputs.uuid }}\"/" $GITHUB_WORKSPACE/deploy/kubernetes/config-map.yaml
    #     sed -i "s/\"ip\": \".*\"/\"ip\": \"${{ github.event.inputs.ip }}\"/" $GITHUB_WORKSPACE/deploy/kubernetes/config-map.yaml

    # - name: Update Secret
    #   run: |
    #     sed -i "s/\"secret\": \".*\"/\"secret\": \"${{ github.event.inputs.secret }}\"/" $GITHUB_WORKSPACE/deploy/kubernetes/secret.yaml

    - name: Install SPDK-CSI using Helm
      run: |
        cd spdk-csi/charts/spdk-csi
        helm install spdk-csi ./ \
          --set csiConfig.simplybk.uuid=${{ github.event.inputs.uuid }} \
          --set csiConfig.simplybk.ip=${{ github.event.inputs.ip }} \
          --set csiSecret.simplybk.secret=${{ github.event.inputs.secret }} \
          --set logicalVolume.pool_name=testing1

    - name: Run tests
      run: make e2e-test
