name: SPDK E2E TEST

on:
  push:
    branches: ['test_for_dynamic_pv']

jobs:
  build:
    name: Build
    runs-on: buildjet-4vcpu-ubuntu-2204
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version: ^1.21
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
      
    - name: Install kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
      
    - name: Authenticate with Kubernetes cluster
      run: |
        mkdir -p ${HOME}/.kube
        echo ${{ secrets.KUBE_CONFIG_DATA }} | base64 --decode >  ${HOME}/.kube/config
       # echo "$KUBE_CONFIG_DATA" | base64 -d > ~/.kube/config
      # env:
      # #   KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}

    - name: Run tests
      run: make e2e-test

